# This is the configuration file for the Eureka Server
server:
  port: 8761 # Eureka default port

spring:
  application:
    name: eureka-server

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false


