# Configuration for energy-service microservice
server:
  port: 8084  # HTTP port for H2, actuator, Eureka

spring:
  application:
    name: energy-service

  datasource:
    url: jdbc:h2:mem:energydb
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  sql:
    init:
      mode: always

  h2:
    console:
      enabled: true
      path: /h2-console

eureka:
  instance:
    prefer-ip-address: true
    hostname: localhost
    statusPageUrlPath: /actuator/info
    healthCheckUrlPath: /actuator/health

  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
    healthcheck:
      enabled: false

grpc:
  server:
    port: 9093  # Dedicated gRPC port for energy-service
    address: 127.0.0.1
